services:

  postgres:
    image: postgis/postgis:16-3.4-alpine

    container_name: catastro-db

    environment:
      POSTGRES_DB: catastro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./Database/01-buildings.sql:/docker-entrypoint-initdb.d/01-buildings.sql:ro

    restart: unless-stopped

    networks:
      - app-network

  gdal:
    image: ghcr.io/osgeo/gdal:ubuntu-small-latest

    container_name: catastro-gdal

    volumes:
      - ./Database/A.ES.SDGC.BU.Viveiro.building.gml:/data/Viveiro.gml:ro
      - ./Database/A.ES.SDGC.BU.Torremolinos.building.gml:/data/Torremolinos.gml:ro
      - ./Database/A.ES.SDGC.BU.Algeciras.building.gml:/data/Algeciras.gml:ro
      - ./Database/A.ES.SDGC.BU.Madrid.building.gml:/data/Madrid.gml:ro
      - ./Database/A.ES.SDGC.BU.ElHierro.building.gml:/data/ElHierro.gml:ro

      - ./Database/02-load-buildings.sh:/02-load-buildings.sh:ro

    depends_on:
      - postgres

    networks:
      - app-network

    entrypoint: ["/bin/bash", "/02-load-buildings.sh"]

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile

    container_name: react-app

    ports:
      - "5173:80"

    depends_on:
      - keycloak
      - postgres
      - backend

    restart: unless-stopped

    networks:
      - app-network


  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile

    container_name: node-api

    ports:
      - "3000:3000"

    volumes:
      - ./Backend:/app
      - /app/node_modules

    depends_on:
      - keycloak
      - postgres

    restart: unless-stopped

    networks:
      - app-network


  keycloak:
    image: quay.io/keycloak/keycloak:26.7

    container_name: keycloak-alpine

    command: start-dev

    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    ports:
      - "8080:8080"

    restart: unless-stopped

    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: